setenv ('SGE_CONTEXT', 'exclusive');
setenv ('SGE_OPT', 'h_rt=48:0:0'); 

c = parcluster ('myriad_R2018b');
myJob = createCommunicatingJob(c, 'Type', 'pool');
num_workers = 20;
myJob.AttachedFiles = {...
    'map_master_script_cluster.m'...
    'run_mle_cluster.m'...
    'run_prior_estimation_cluster.m'...
    'run_map_cluster.m'...
    'fit_1lr1t.m'...
    'fit_1lr2t.m'...
    'fit_2lr1t.m'...
    'fit_2lr2t.m'...
    'fit_1lr1s.m'...
    'fit_2lr1s.m'...
    'fit_1lr2s.m'...
    'fit_2lr2s.m'...
    'fit_1lr1s1lapse.m'...
    'fit_2lr1s1lapse.m'...
    'fit_1lr2s1lapse.m'...
    'fit_2lr2s1lapse.m'...
    'fit_1lr1s1lapse1bias_gng.m'...
    'fit_1lr1s1lapse2bias_gng.m'...
    'fit_1lr1s1lapse3bias_gng.m'...
    'fit_2lr2s1lapse1bias_gng.m'...
    'fit_2lr2s1lapse2bias_gng.m'...
    'fit_2lr2s1lapse3bias_gng.m'...
    '../../simulated_data/simulated_data_t1.csv'...
    '../../simulated_data/simulated_data_t2.csv'...
    '../../simulated_data/simulated_data_t3.csv'...
    '../../simulated_data/simulated_data_t4.csv'...
    };
myJob.NumWorkersRange = [1, num_workers];
task = createTask (myJob, @map_master_script, 1, {});
submit(myJob);