---
title: "R Notebook"
output: html_notebook
---

This is the setup chunk.

```{r}
#clears environment
rm(list=ls())

#libraries
library('plyr')
library('rstan')
library('loo')
library('afex')
library('R.matlab')
library('RColorBrewer')

#setup params
cluster=TRUE #if loading in from cluster

workingdir='C:/Users/apike/OneDrive - University College London/metaRL/'

source(paste0(workingdir,'scripts/bic.R'))
source(paste0(workingdir,'scripts/effect_sizes_text.R'))
source(paste0(workingdir,'scripts/plottext_cohend.R'))

```

Load in simulated data.
```{r}
load(file=paste0(workingdir,'simulated_data/data_task1')) #doesn't matter which one as you dont' use choices
simulated_data<-as.data.frame(simulated_data)
colnames(simulated_data)<- c('study','pat_con','id','trial','reward','pun','choices')
simulated_data<-transform(simulated_data,fullid=paste(study,id,sep='.'))
data_details<-simulated_data[simulated_data$trial==1,]
nsub_overall=length(unique(simulated_data$fullid))
ntrials=max(simulated_data$trial)

```

Use a script to compare model fits
Task 1
```{r}
task='t1'

source('analyse_modelfits_vba_singleprior.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse'),c(2,3,3,4,2,3,3,4,3,4,4,5))
analyse_modelfits_vba_singleprior(workingdir,model_details,ntrials=ntrials,task=task)
```
Task 2
```{r}

task='t2'

source('analyse_modelfits_vba_singleprior.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse'),c(2,3,3,4,2,3,3,4,3,4,4,5))
analyse_modelfits_vba_singleprior(workingdir,model_details,ntrials=ntrials,task=task)

```
Task 3
```{r}
task='t3'

source('analyse_modelfits_vba_singleprior.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse'),c(2,3,3,4,2,3,3,4,3,4,4,5))
analyse_modelfits_vba_singleprior(workingdir,model_details,ntrials=ntrials,task=task)

```
Task 4
```{r}

task='t4'

source('analyse_modelfits_vba_singleprior.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse','1lr1s1lapse1bias','1lr1s1lapse2bias','1lr1s1lapse3bias','2lr2s1lapse1bias','2lr2s1lapse2bias','2lr2s1lapse3bias'),c(2,3,3,4,2,3,3,4,3,4,4,5,4,5,6,6,7,8))
analyse_modelfits_vba_singleprior(workingdir,model_details,ntrials=ntrials,task=task)

```
Overall winning model
```{r}
load(paste0(workingdir,'/big_outputs/bic_df_vba_sp_t1'))
bic_df_t1<-bic_df
load(paste0(workingdir,'/big_outputs/bic_df_vba_sp_t2'))
bic_df_t2<-bic_df
load(paste0(workingdir,'/big_outputs/bic_df_vba_sp_t3'))
bic_df_t3<-bic_df
load(paste0(workingdir,'/big_outputs/bic_df_vba_sp_t4'))
bic_df_t4<-bic_df
bic_df<-data.frame(cbind(colSums(bic_df_t1),colSums(bic_df_t2),colSums(bic_df_t3),colSums(bic_df_t4)[1:12]))
names(bic_df)<-c('task1','task2','task3','task4')
min<-min(rowSums(bic_df))
max<-max(rowSums(bic_df))
model_names<-rownames(bic_df)
bic_df$model<-factor(model_names,levels=c(model_names),ordered=TRUE)
bic_df_long<-melt(bic_df)

modelcolours<-colorRampPalette(brewer.pal(9,'Set1'))(18)[1:length(bic_df$model)]
df<-data.frame(model_names,rowSums(bic_df[,1:4]))
names(df)<-c('model','total')
df$model<-factor(df$model,levels=c(model_names),ordered=TRUE)
bic_sums_unordered<-ggplot(df,aes(x=model,y=total,fill=model,label=model))+
  geom_bar(stat='identity')+
  labs(x='Model',y='Total BIC')+
  theme_classic()+
  theme(legend.position='none',axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+
  coord_cartesian(ylim = c(round_any(min(df$total),1000,floor), 
                           round_any(max(df$total),1000,ceiling)))+
  geom_text(data = df[which.min(df$total),], label = "*", nudge_y=100) +
  scale_fill_manual(values=modelcolours)
ggsave(paste0(workingdir,'/figures/bic_sums_vba_unordered_overall_sp.png'),scale=0.5,width=10,height=10)
  
```

Analyse overall (omnibus ANOVA)

```{r}
winning_model<-'2lr2s'

load(paste0(workingdir,'stan_outputs/fit_',winning_model,'_ALL_t1.RData'))
fit_t1<-fit_2lr2s_ALL
load(paste0(workingdir,'stan_outputs/fit_',winning_model,'_ALL_t2.RData'))
fit_t2<-fit_2lr2s_ALL
load(paste0(workingdir,'stan_outputs/fit_',winning_model,'_ALL_t3.RData'))
fit_t3<-fit_2lr2s_ALL
load(paste0(workingdir,'stan_outputs/fit_',winning_model,'_ALL_t4.RData'))
fit_t4<-fit_2lr2s_ALL
```

Win learning rate

```{r}
alphawin_t1<-get_posterior_mean(fit_t1,'alpha_win')
alphawin_t2<-get_posterior_mean(fit_t2,'alpha_win')
alphawin_t3<-get_posterior_mean(fit_t3,'alpha_win')
alphawin_t4<-get_posterior_mean(fit_t4,'alpha_win')


alpha_df<-cbind(alphawin_t1,alphawin_t2,alphawin_t3,alphawin_t4)

alpha_df<-data.frame(data_details,alpha_df)

alpha_df<-melt(alpha_df,id.vars = c(1:ncol(data_details)))

names(alpha_df)<-c(names(data_details),'task','win learning rate')

alpha_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`win learning rate`),2),iqr=round(IQR(`win learning rate`),2))

alpha_df$task<-as.numeric(alpha_df$task)
alpha_df$pat_con<-as.factor(alpha_df$pat_con)
alpha_df$task<-as.factor(alpha_df$task)
alpha_df$study<-as.factor(alpha_df$study)

model<-permuco::aovperm(`win learning rate` ~ pat_con * study * task + Error(fullid/(task)), data=alpha_df, method = "Rd_kheradPajouh_renaud")
print(model)

effect_sizes_text(workingdir,'omnibus','single','vba','win learning rate','all',alpha_df)

d<-cohen.d(alpha_df$`win learning rate`[alpha_df$pat_con==1],alpha_df$`win learning rate`[alpha_df$pat_con==0])
print(d)
d<-round(d$estimate,2)

plottext<-plottext_cohend(model,d)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
p1<-ggplot(alpha_df,aes(x=pat_con,y=`win learning rate`,group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE,color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Win learning rate')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        scale_fill_manual(values=c('#FC766AFF','#5B84B1FF'))+
        annotate(geom='text',x=1.5,y=1.1,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 1.02, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 1.05, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 1.02, yend = 1.05,
                     colour = "black")
ggsave(paste0(workingdir,'/figures/alphawin_overall_sp.png'), scale=0.6)

```

Loss learning rate

```{r}
alphaloss_t1<-get_posterior_mean(fit_t1,'alpha_loss')
alphaloss_t2<-get_posterior_mean(fit_t2,'alpha_loss')
alphaloss_t3<-get_posterior_mean(fit_t3,'alpha_loss')
alphaloss_t4<-get_posterior_mean(fit_t4,'alpha_loss')


alpha_df<-cbind(alphaloss_t1,alphaloss_t2,alphaloss_t3,alphaloss_t4)

alpha_df<-data.frame(data_details,alpha_df)

alpha_df<-melt(alpha_df,id.vars = c(1:ncol(data_details)))

names(alpha_df)<-c(names(data_details),'task','loss learning rate')

alpha_df$task<-as.numeric(alpha_df$task)
alpha_df$pat_con<-as.factor(alpha_df$pat_con)
alpha_df$task<-as.factor(alpha_df$task)
alpha_df$study<-as.factor(alpha_df$study)

alpha_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`loss learning rate`),2),iqr=round(IQR(`loss learning rate`),2))


model<-permuco::aovperm(`loss learning rate` ~ pat_con * study * task + Error(fullid/(task)), data=alpha_df, method = "Rd_kheradPajouh_renaud")
print(model)

effect_sizes_text(workingdir,'omnibus','single','vba','loss learning rate','all',alpha_df)

d<-cohen.d(alpha_df$`loss learning rate`[alpha_df$pat_con==1],alpha_df$`loss learning rate`[alpha_df$pat_con==0])
print(d)
d<-round(d$estimate,2)

plottext<-plottext_cohend(model,d)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
p2<-ggplot(alpha_df,aes(x=pat_con,y=`loss learning rate`,group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE, color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Loss learning rate')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        annotate(geom='text',x=1.5,y=1.1,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 1.02, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 1.05, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 1.02, yend = 1.05,
                     colour = "black")+
        scale_fill_manual(values=c('#FC766AFF','#5B84B1FF'))+
ggsave(paste0(workingdir,'/figures/alphaloss_overall_sp.png'), scale=0.6)

```
Win sensitivity

```{r}
sensitivitywin_t1<-get_posterior_mean(fit_t1,'sensitivity_win')
sensitivitywin_t2<-get_posterior_mean(fit_t2,'sensitivity_win')
sensitivitywin_t3<-get_posterior_mean(fit_t3,'sensitivity_win')
sensitivitywin_t4<-get_posterior_mean(fit_t4,'sensitivity_win')


sensitivity_df<-cbind(sensitivitywin_t1,sensitivitywin_t2,sensitivitywin_t3,sensitivitywin_t4)

sensitivity_df<-data.frame(data_details,sensitivity_df)

sensitivity_df<-melt(sensitivity_df,id.vars = c(1:ncol(data_details)))

names(sensitivity_df)<-c(names(data_details),'task','win sensitivity')

sensitivity_df$task<-as.numeric(sensitivity_df$task)
sensitivity_df$pat_con<-as.factor(sensitivity_df$pat_con)
sensitivity_df$task<-as.factor(sensitivity_df$task)
sensitivity_df$study<-as.factor(sensitivity_df$study)

sensitivity_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`win sensitivity`),2),iqr=round(IQR(`win sensitivity`),2))


model<-permuco::aovperm(`win sensitivity` ~ pat_con * study * task + Error(fullid/(task)), data=sensitivity_df, method = "Rd_kheradPajouh_renaud")
print(model)

effect_sizes_text(workingdir,'omnibus','single','vba','win sensitivity','all',sensitivity_df)

d<-cohen.d(sensitivity_df$`win sensitivity`[sensitivity_df$pat_con==1],sensitivity_df$`win sensitivity`[alpha_df$pat_con==0])
print(d)
d<-round(d$estimate,2)

plottext<-plottext_cohend(model,d)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
p3<-ggplot(sensitivity_df,aes(x=pat_con,y=log(`win sensitivity`),
                              group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE, color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Log win sensitivity')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        scale_fill_manual(values=c('#FC766AFF','#5B84B1FF'))+
        scale_y_continuous(breaks=c(-4,-2,0,2,4),limits=c(-3,5))+
        annotate(geom='text',x=1.5,y=5,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 4, yend = 4.5,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 4.5, yend = 4.5,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 4, yend = 4.5,
                     colour = "black")
ggsave(paste0(workingdir,'/figures/sensitivitywin_overall_sp.png'), scale=0.6)

```

Loss sensitivity

```{r}
sensitivityloss_t1<-get_posterior_mean(fit_t1,'sensitivity_loss')
sensitivityloss_t2<-get_posterior_mean(fit_t2,'sensitivity_loss')
sensitivityloss_t3<-get_posterior_mean(fit_t3,'sensitivity_loss')
sensitivityloss_t4<-get_posterior_mean(fit_t4,'sensitivity_loss')


sensitivity_df<-cbind(sensitivityloss_t1,sensitivityloss_t2,sensitivityloss_t3,sensitivityloss_t4)

sensitivity_df<-data.frame(data_details,sensitivity_df)

sensitivity_df<-melt(sensitivity_df,id.vars = c(1:ncol(data_details)))

names(sensitivity_df)<-c(names(data_details),'task','loss sensitivity')

sensitivity_df$task<-as.numeric(sensitivity_df$task)
sensitivity_df$pat_con<-as.factor(sensitivity_df$pat_con)
sensitivity_df$task<-as.factor(sensitivity_df$task)
sensitivity_df$study<-as.factor(sensitivity_df$study)

sensitivity_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`loss sensitivity`),2),iqr=round(IQR(`loss sensitivity`),2))

model<-permuco::aovperm(`loss sensitivity` ~ pat_con * study * task + Error(fullid/(task)), data=sensitivity_df, method = "Rd_kheradPajouh_renaud")
print(model)

effect_sizes_text(workingdir,'omnibus','single','vba','loss sensitivity','all',sensitivity_df)

d<-cohen.d(sensitivity_df$`loss sensitivity`[sensitivity_df$pat_con==1],sensitivity_df$`loss sensitivity`[alpha_df$pat_con==0])
print(d)
d<-round(d$estimate,2)

plottext<-plottext_cohend(model,d)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
p4<-ggplot(sensitivity_df,aes(x=pat_con,y=log(`loss sensitivity`),
                              group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE, color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Log loss sensitivity')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        scale_fill_manual(values=c('#FC766AFF','#5B84B1FF'))+
        scale_y_continuous(breaks=c(-4,-2,0,2,4),limits=c(-3,5))+
        annotate(geom='text',x=1.5,y=5,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 4, yend = 4.5,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 4.5, yend = 4.5,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 4, yend = 4.5,
                     colour = "black")
ggsave(paste0(workingdir,'/figures/sensitivityloss_overall_sp.png'), scale=0.6)

```

Combine all plots together

```{r}
library('patchwork')

(p1 + p2)/(p3 + p4) + plot_annotation(tag_levels='A',) + plot_layout(guides='collect') & labs(fill='Group') & scale_fill_manual(values=c('#FC766AFF','#5B84B1FF'),labels=c('Control','Patient'))

ggsave(paste0(workingdir,'/figures/params_overall_sp.png'), scale=0.6, width=12, height =14)

```