---
title: "Analysis before simulation"
output: html_notebook
---

Libraries

```{r}
rm(list=ls())

library('afex')
library('ggplot2')
library('patchwork')
library('permuco')
library('effsize')
library('tidyverse')
library('meta')
library('gridGraphics')
library('gridExtra')

workingdir='C:/Users/apike/OneDrive - University College London/metaRL/'

source(paste0(workingdir,'scripts/plottext_cohend.R'))
```


Load parameters

```{r}
files<-list.files(paste0(workingdir,'/raw_parameters/'))
files_long<-list.files(paste0(workingdir,'/raw_parameters/'),full.names=TRUE)
loading<-lapply(files_long, load, .GlobalEnv)

```

Make dataframe

```{r}
paper_params_full<-bind_rows(list(lapply(files,get)),.id='study')%>%
  relocate(group,.after=study)

paper_params<-paper_params_full%>%
  select(group,study,alpha,alphawin,alphaloss,beta,beta2,tau)%>%
  filter(alpha<1|is.na(alpha))%>%
  filter(alphawin<1|is.na(alphawin))%>%
  filter(alphaloss<1|is.na(alphaloss))%>%#removes White subs with alpha>1
  mutate(beta=ifelse(!is.na(tau),1/tau,beta))%>% #converts temp to inverse temp
  mutate(beta=ifelse(!is.na(beta2),10+beta2,beta)) #converts Dombrovski 10-beta 

paper_params$group<-as.factor(paper_params$group)

#sanity check
length(files)==max(as.numeric(as.character(paper_params$study)))
```

Descriptive statistics

```{r}
paper_params %>%
  group_by(group)%>%
  summarise(median=round(median(alphawin,na.rm=TRUE),2),iqr=round(IQR(alphawin,na.rm=TRUE),2))

paper_params %>%
  group_by(group)%>%
  summarise(median=round(median(alphaloss,na.rm=TRUE),2),iqr=round(IQR(alphaloss,na.rm=TRUE),2))

```
Conventional meta-analysis

```{r}
paper_params<-paper_params%>%
  mutate(study=recode(study,`1`='Aylward et al. 2019', 
                      `2`='Blanco et al. 2013',
                      `3`='Brown et al. 2018',
                      `4`='Cavanagh et al. 2019', 
                      `5`='Chase et al. 2010', 
                      `6`='Dombrovski et al. 2010', 
                      `7`= 'Dombrovski et al. 2013', 
                      `8`='Dombrovski et al. 2019',
                      `9`='Frey et al. 2019',
                      `10`='Gagne et al. 2020',
                      `11`='Gradin et al. 2011',
                      `12`='Huang et al. 2017',
                      `13`='Huys et al. 2013',
                      `14`='Khdour et al. 2016',
                      `15`='Kumar et al. 2018',
                      `16`='Kunisato et al. 2012', 
                      `17`='Lamba et al. 2020',
                      `18`='Liu et al. 2017',
                      `19`='Millner et al. 2019',
                      `20`='Mkrtchian et al. 2017',
                      `21`='Moutoussis et al. 2018',
                      `22`='Mukherjee et al. 2020',
                      `23`='Myers et al. 2013',
                      `24`='Ross et al. 2018',
                      `25`='Rupprechter et al. 2018', 
                      `26`='Rupprechter et al. 2020', 
                      `27`='White et al. 2017' ))%>%
  mutate(disorder=case_when(
                         study=='Aylward et al. 2019'|study=='Gagne et al. 2020'|study=='Mkrtchian et al. 2017' ~ 'mixed',
                         study=='Blanco et al. 2013'|study=='Cavanagh et al. 2019'|study=='Chase et al. 2010'|study=='Dombrovski et al. 2010'|study=='Dombrovski et al. 2013'|study=='Dombrovski et al. 2019'|study=='Frey et al. 2019'|study=='Gradin et al. 2011'|study=='Huys et al. 2013'|study=='Kumar et al. 2018'|study=='Liu et al. 2017'|study=='Millner et al. 2019'|study=='Moutoussis et al. 2018'|study=='Mukherjee et al. 2020'|study=='Rupprechter et al. 2018'|study=='Rupprechter et al. 2020' ~ 'depression',
                         study=='Huang et al. 2017'|study=='Khdour et al. 2016'|study=='Kunisato et al. 2012'|study=='Lamba et al. 2020'|study=='White et al. 2017'~'anxiety',
                         study=='Brown et al. 2018'|study=='Myers et al. 2013'|study=='Ross et al. 2018'|study=='White et al. 2017' ~ 'PTSD'))

summary_alpha<-paper_params%>%
  group_by(group,study,disorder)%>%
  summarize(n=sum(!is.na(alpha)),
            mean=mean(alpha,na.rm=TRUE),
            sd=sd(alpha,na.rm=TRUE))%>%
  pivot_wider(names_from=group,id_cols=c(study,disorder),values_from=c(n,mean,sd))

meta.alpha<- metacont(n.e=n_1,
                  mean.e=mean_1,
                  sd.e=sd_1,
                  n.c=n_0,
                  mean.c=mean_0,
                  sd.c=sd_0,
                  data=summary_alpha,
                  studlab=paste(study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  prediction=TRUE,
                  sm="SMD")
meta.alpha


summary_beta<-paper_params%>%
  group_by(group,study,disorder)%>%
  summarize(n=sum(!is.na(beta)),
            mean=mean(beta,na.rm=TRUE),
            sd=sd(beta,na.rm=TRUE))%>%
  pivot_wider(names_from=group,id_cols=c(study,disorder),values_from=c(n,mean,sd))

meta.beta<- metacont(n.e=n_1,
                  mean.e=mean_1,
                  sd.e=sd_1,
                  n.c=n_0,
                  mean.c=mean_0,
                  sd.c=sd_0,
                  data=summary_beta,
                  studlab=paste(study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  prediction=TRUE,
                  sm="SMD")
meta.beta


summary_alphawin<-paper_params%>%
  group_by(group,study,disorder)%>%
  summarize(n=sum(!is.na(alphawin)),
            mean=mean(alphawin,na.rm=TRUE),
            sd=sd(alphawin,na.rm=TRUE))%>%
  pivot_wider(names_from=group,id_cols=c(study,disorder),values_from=c(n,mean,sd))

meta.alphawin<- metacont(n.e=n_1,
                  mean.e=mean_1,
                  sd.e=sd_1,
                  n.c=n_0,
                  mean.c=mean_0,
                  sd.c=sd_0,
                  data=summary_alphawin,
                  studlab=paste(study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  prediction=TRUE,
                  sm="SMD")

meta.alphawin

summary_alphaloss<-paper_params%>%
  group_by(group,study,disorder)%>%
  summarize(n=sum(!is.na(alphaloss)),
            mean=mean(alphaloss,na.rm=TRUE),
            sd=sd(alphaloss,na.rm=TRUE))%>%
  pivot_wider(names_from=group,id_cols=c(study,disorder),values_from=c(n,mean,sd))


meta.alphaloss<- metacont(n.e=n_1,
                  mean.e=mean_1,
                  sd.e=sd_1,
                  n.c=n_0,
                  mean.c=mean_0,
                  sd.c=sd_0,
                  data=summary_alphaloss,
                  studlab=paste(study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  prediction=TRUE,
                  sm="SMD")
meta.alphaloss


```
Subgroup analyses
```{r}
update.meta(meta.alpha, 
            byvar = disorder, 
            tau.common = FALSE)

update.meta(meta.beta, 
            byvar = disorder, 
            tau.common = FALSE)

update.meta(meta.alphawin, 
            byvar = disorder, 
            tau.common = FALSE)

update.meta(meta.alphaloss, 
            byvar = disorder, 
            tau.common = FALSE)

```

Make forest plots
```{r}
source(paste0(workingdir,'/scripts/custom_forestplot.R'))
#make forest plots

conventional_forest_lr<-custom_forestplot(meta.alpha,'random')+
  ggtitle('Learning rate')
  ggsave(filename=paste0(workingdir,'/figures/conventional_forest_lr.png'))

conventional_forest_beta<-custom_forestplot(meta.beta,'random')+
  ggtitle('Inverse temperature')
  ggsave(filename=paste0(workingdir,'/figures/conventional_forest_beta.png'))

conventional_forest_winlr<-custom_forestplot(meta.alphawin,'random')+
  ggtitle('Reward learning rate')
  ggsave(filename=paste0(workingdir,'/figures/conventional_forest_winlr.png'))

conventional_forest_losslr<-custom_forestplot(meta.alphaloss,'random')+
  ggtitle('Punishment learning rate')
  ggsave(filename=paste0(workingdir,'/figures/conventional_forest_losslr.png'))

(conventional_forest_lr+conventional_forest_beta)/(conventional_forest_winlr+conventional_forest_losslr)+ plot_annotation(tag_levels='A')+plot_layout(guides='collect')

ggsave(filename=paste0(workingdir,'/figures/meta_forest_presim.png'),width=15,height=8)
ggsave(filename=paste0(workingdir,'/figures/meta_forest_presim.pdf'),width=15,height=8)

(conventional_forest_lr)+(conventional_forest_winlr)+(conventional_forest_losslr)+ plot_annotation(tag_levels='A')+plot_layout(guides='collect')

ggsave(filename=paste0(workingdir,'/figures/meta_forest_presim_lr.png'),width=15,height=6)
ggsave(filename=paste0(workingdir,'/figures/meta_forest_presim_lr.pdf'),width=15,height=6)

conventional_forest_beta
ggsave(filename=paste0(workingdir,'/figures/meta_forest_presim_beta.png'),width=8,height=8)
ggsave(filename=paste0(workingdir,'/figures/meta_forest_presim_beta.pdf'),width=8,height=8)

#for talk
layout <- c(
  area(t = 1, l = 2, b = 2, r = 3),
  area(t = 3, l = 1, b = 4, r = 2),
  area(t = 3, l = 3, b = 4, r = 5)
)
(conventional_forest_lr+conventional_forest_winlr+conventional_forest_losslr)+ plot_layout(design=layout)+plot_annotation(tag_levels='A')&theme(legend.position = 'none')

ggsave(filename=paste0(workingdir,'/figures/meta_forest_presim_fortalk.png'),width=15,height=8,scale=1)
```

Assess publication bias

```{r}
bias_alpha<-metabias(meta.alpha, method.bias = "Pustejovsky")
bias_alpha
bias_alpha$estimate['intercept'] - qnorm(0.975) *bias_alpha$estimate['se.intercept']
bias_alpha$estimate['intercept'] + qnorm(0.975) *bias_alpha$estimate['se.intercept']

bias_beta<-metabias(meta.beta, method.bias = "Pustejovsky")
bias_beta
bias_beta$estimate['intercept'] - qnorm(0.975) *bias_beta$estimate['se.intercept']
bias_beta$estimate['intercept'] + qnorm(0.975) *bias_beta$estimate['se.intercept']

bias_alphawin<-metabias(meta.alphawin, method.bias = "Pustejovsky")
bias_alphawin
bias_alphawin$estimate['intercept'] - qnorm(0.975) *bias_alphawin$estimate['se.intercept']
bias_alphawin$estimate['intercept'] + qnorm(0.975) *bias_alphawin$estimate['se.intercept']

bias_alphaloss<-metabias(meta.alphaloss, method.bias = "Pustejovsky")
bias_alphaloss
bias_alphaloss$estimate['intercept'] - qnorm(0.975) *bias_alphaloss$estimate['se.intercept']
bias_alphaloss$estimate['intercept'] + qnorm(0.975) *bias_alphaloss$estimate['se.intercept']

#make funnel plots
par(mfrow=c(2,2))
funnel(meta.alpha, xlab="Hedges' g", 
       contour = c(.95,.975,.99),
       col.contour=c("darkblue","blue","lightblue"))
title(main='Learning rate')
funnel(meta.beta, xlab="Hedges' g", 
       contour = c(.95,.975,.99),
       col.contour=c("darkblue","blue","lightblue"))
title(main='Inverse temperature')
funnel(meta.alphawin, xlab="Hedges' g", 
       contour = c(.95,.975,.99),
       col.contour=c("darkblue","blue","lightblue"))
title(main='Reward learning rate')
funnel(meta.alphaloss, xlab="Hedges' g", 
       contour = c(.95,.975,.99),
       col.contour=c("darkblue","blue","lightblue"))
title(main='Punishment learning rate')
par(fig=c(0, 1, 0, 1), oma=c(0, 0, 0, 0), mar=c(0, 0, 0, 0), new=TRUE)
plot(0, 0, type='n', bty='n', xaxt='n', yaxt='n')
legend(-0.1,-0.8, c("p<0.050", "p<0.025", "p<0.010"),bty = "n",
       fill=c("darkblue","blue","lightblue"),xpd=NA)
dev.copy(png,paste0(workingdir,'/figures/funnelplots.png'))
dev.off()

```



