---
title: "Generate and recover notebook: STAN"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Libraries
```{r}
rm(list=ls())

library('R.matlab')
library('cmdstanr')
library('ggplot2')
library('dplyr')
library('patchwork')

workingdir='C:/Users/apike/OneDrive - University College London/metaRL/'
datadir='C:/Users/apike/OneDrive - University College London/metaRL/generate_recover/'
scriptdir='C:/Users/apike/OneDrive - University College London/metaRL/scripts/'
modeldir='C:/Users/apike/OneDrive - University College London/metaRL/scripts/models/'
ntrials=150
```


Generate parameters

```{r}
#don't run if you don't want to generate new parameters! can load in saved ones later if that's preferred.

n=1000 #number of 'agents' you want to create

alpha<-rbeta(n,1,1)

alphaloss<-rbeta(n,1,1)
  
beta<-rgamma(n,5,1)
  
betaloss<-rgamma(n,5,1)

rewsens<-rgamma(n,3,1)

punsens<-rgamma(n,3,1)

lapse<-rbeta(n,0.5,1.5)

gobias<-rgamma(n,3,1)

appbias<-rgamma(n,3,1)

avbias<-rgamma(n,3,1)

hist(alpha)
hist(alphaloss)
hist(beta)
hist(betaloss)
hist(rewsens)
hist(punsens)
hist(lapse)
hist(gobias)
hist(appbias)
hist(avbias)

generated_parameters=list(alpha=alpha, alphaloss=alphaloss, beta=beta, betaloss=betaloss, rewsens=rewsens, punsens=punsens, lapse=lapse, gobias=gobias, appbias=appbias,avbias=avbias)

save(generated_parameters, file=paste0(workingdir,'/simulated_data/generated_params'))
```

Load generated parameters
```{r}
load('C:/Users/apike/OneDrive - University College London/metaRL/simulated_data/generated_params')
ntrials<-150
n=500
```

Generate synthetic data for genrec: task 1
```{r}
source(paste0(scriptdir,'gen_rec_dataonly.R'))
model1='1lr1s1lapse'

dir.create(paste0(datadir,model1,'/'))
load(paste0(workingdir,'tasks/task1'))
data_t1<-gen_rec_dataonly(n,task1,model1,'t1',0,workingdir)
save(data_t1,file=paste0(datadir,model1,'/data_t1'))
data_t1<-as.data.frame(data_t1)
colnames(data_t1)<- c('study','pat/con','id','trial','reward','pun','choices')
data_t1<-transform(data_t1,fullid=paste(study,id,sep='.'))
data_t1$study<-as.numeric(data_t1$study)
data_t1$fullid<-rep(seq(1:length(unique(data_t1$fullid))),each=ntrials)
directory<-paste0(datadir,model1)
write.csv(data_t1,paste0(directory,'/data_t1.csv'))
source(paste0(scriptdir,'stanify_data.R'))
stanify_data('t1',directory)
```
Task 2
```{r}
source(paste0(scriptdir,'gen_rec_dataonly.R'))
model2='1lr1s1lapse'


dir.create(paste0(datadir,model2,'/'))
load(paste0(workingdir,'tasks/task2'))
data_t2<-gen_rec_dataonly(n,task2,model2,'t2',0,workingdir)
save(data_t2,file=paste0(datadir,model2,'/data_t2'))
data_t2<-as.data.frame(data_t2)
colnames(data_t2)<- c('study','pat/con','id','trial','reward','pun','choices')
data_t2<-transform(data_t2,fullid=paste(study,id,sep='.'))
data_t2$study<-as.numeric(data_t2$study)
data_t2$fullid<-rep(seq(1:length(unique(data_t2$fullid))),each=ntrials)
directory<-paste0(datadir,model2)
write.csv(data_t2,paste0(directory,'/data_t2.csv'))
source(paste0(scriptdir,'stanify_data.R'))
stanify_data('t2',directory)
```
Task 3
```{r}
source(paste0(scriptdir,'gen_rec_dataonly.R'))
model3='1lr1s1lapse'


dir.create(paste0(datadir,model3,'/'))
load(paste0(workingdir,'tasks/task3'))
data_t3<-gen_rec_dataonly(n,task3,model3,'t3',0,workingdir)
save(data_t3,file=paste0(datadir,model3,'/data_t3'))
data_t3<-as.data.frame(data_t3)
colnames(data_t3)<- c('study','pat/con','id','trial','reward','pun','choices')
data_t3<-transform(data_t3,fullid=paste(study,id,sep='.'))
data_t3$study<-as.numeric(data_t3$study)
data_t3$fullid<-rep(seq(1:length(unique(data_t3$fullid))),each=ntrials)
directory<-paste0(datadir,model3)
write.csv(data_t3,paste0(directory,'/data_t3.csv'))
source(paste0(scriptdir,'stanify_data.R'))
stanify_data('t3',directory)
```
Task 4
```{r}
source(paste0(scriptdir,'gen_rec_dataonly.R'))
model4='1lr1s1lapse'


dir.create(paste0(datadir,model4,'/'))
load(paste0(workingdir,'tasks/task4'))
data_t4<-gen_rec_dataonly(n,task4,model4,'t4',1,workingdir)
save(data_t4,file=paste0(datadir,model4,'/data_t4'))
data_t4<-as.data.frame(data_t4)
colnames(data_t4)<- c('study','pat_con','id','trial','stim','go_outcome','nogo_outcome','choices')
data_t4<-transform(data_t4,fullid=paste(study,id,sep='.'))
data_t4$study<-as.numeric(data_t4$study)
data_t4$fullid<-rep(seq(1:length(unique(data_t4$fullid))),each=ntrials)
directory<-paste0(datadir,model4)
write.csv(data_t4,paste0(directory,'/data_t4.csv'))
source(paste0(scriptdir,'stanify_data_gng.R'))
stanify_data_gng('t4',directory)
```

Now run task1 using vb 
```{r}
library('cmdstanr')

model1='1lr1s1lapse'

load(paste0(datadir,model1,'/con_data_t1.RData'))

stanname=paste0('metaRL_',model1,'.stan')
stanfile <- paste0(modeldir,stanname)
model<-cmdstan_model(stanfile)
fit_t1 <- model$variational(data = con_data_t1,tol_rel_obj = 0.001)
fit_t1$save_object(file=file.path(datadir,model1,'/fit_t1.RDS'))
```

Run task 2

```{r}
library('rstan')

model2='1lr1s1lapse'

load(paste0(datadir,model2,'/con_data_t2.RData'))

stanname=paste0('metaRL_',model2,'.stan')
stanfile <- paste0(modeldir,stanname)
model<-cmdstan_model(stanfile)
fit_t2 <- model$variational(data = con_data_t2, tol_rel_obj = 0.001)
fit_t2$save_object(file=file.path(datadir,model2,'/fit_t2.RDS'))
```
Task 3
```{r}
library('cmdstanr')

model3='1lr1s1lapse'

load(paste0(datadir,model3,'/con_data_t3.RData'))

stanname=paste0('metaRL_',model3,'.stan')
stanfile <- paste0(modeldir,stanname)
model<-cmdstan_model(stanfile)
fit_t3 <- model$variational(data = con_data_t3, tol_rel_obj = 0.001)
fit_t3$save_object(file=file.path(datadir,model3,'/fit_t3.RDS'))
```
Task 4
```{r}
library('cmdstanr')

model4='1lr1s1lapse'

load(paste0(datadir,model4,'/con_data_t4.RData'))

stanname=paste0('metaRL_',model4,'_gng.stan')
stanfile <- paste0(modeldir, stanname)
model<-cmdstan_model(stanfile)
fit_t4 <- model$variational(data = con_data_t4, tol_rel_obj = 0.001)
#fit_t4<-model$sample(data=con_data_t4,chains = 4,parallel_chains = 4)
fit_t4$save_object(file=file.path(datadir,model4,'/fit_t4.RDS'))
```



Analyse results for genrec: task 1
```{r}
model1<-'1lr1s1lapse'
fit_t1<-readRDS(file=file.path(datadir,model1,'/fit_t1.RDS'))

source(paste0(scriptdir,'/analyse_recoverability_vb.R'))
source(paste0(scriptdir,'/confusion_matrix.R'))

params_t1<-analyse_recoverability_vb(model1,ntrials,'t1')
original<-do.call(cbind,lapply(params_t1,function(x) x[,1]))
estimated<-do.call(cbind,lapply(params_t1,function(x) x[,2]))
colnames(original)<-lapply(params_t1, function(x) gsub("[[:digit:]]","",rownames(x)[1])) #gets column names
colnames(estimated)<-colnames(original)
t1_matrix<-confusion_matrix(original,estimated,paramnames=c('learning rate','sensitivity','lapse'))+
  labs(title='Task 1')
ggsave(paste0(datadir,model1,'/t1_confusion_matrix.png'),t1_matrix)

```
Task 2
```{r}
model2<-'1lr1s1lapse'
fit_t2<-readRDS(file=file.path(datadir,model2,'/fit_t2.RDS'))

source(paste0(scriptdir,'/analyse_recoverability_vb.R'))
source(paste0(scriptdir,'/confusion_matrix.R'))

params_t2<-analyse_recoverability_vb(model2,ntrials,'t2')
original<-do.call(cbind,lapply(params_t2,function(x) x[,1]))
estimated<-do.call(cbind,lapply(params_t2,function(x) x[,2]))
colnames(original)<-lapply(params_t2, function(x) gsub("[[:digit:]]","",rownames(x)[1])) #gets column names
colnames(estimated)<-colnames(original)
t2_matrix<-confusion_matrix(original,estimated,paramnames=c('learning rate','sensitivity','lapse'))+
  labs(title='Task 2')
ggsave(paste0(datadir,model2,'/t2_confusion_matrix.png'),t2_matrix)
```
Task 3
```{r}
model3<-'1lr1s1lapse'
fit_t3<-readRDS(file=file.path(datadir,model3,'/fit_t3.RDS'))

source(paste0(scriptdir,'/analyse_recoverability_vb.R'))
source(paste0(scriptdir,'/confusion_matrix.R'))

params_t3<-analyse_recoverability_vb(model3,ntrials,'t3')
original<-do.call(cbind,lapply(params_t3,function(x) x[,1]))
estimated<-do.call(cbind,lapply(params_t3,function(x) x[,2]))
colnames(original)<-lapply(params_t3, function(x) gsub("[[:digit:]]","",rownames(x)[1])) #gets column names
colnames(estimated)<-colnames(original)
t3_matrix<-confusion_matrix(original,estimated,paramnames=c('learning rate','sensitivity','lapse'))+
  labs(title='Task 3')
ggsave(paste0(datadir,model3,'/t3_confusion_matrix.png'),t3_matrix)

```
Task 4
```{r}
model4<-'1lr1s1lapse'
fit_t4<-readRDS(file=file.path(datadir,model4,'/fit_t4.RDS'))

source(paste0(scriptdir,'/analyse_recoverability_vb.R'))
source(paste0(scriptdir,'/confusion_matrix.R'))

params_t4<-analyse_recoverability_vb(model4,ntrials,'t4')
#params_t4<-analyse_recoverability(model4,ntrials,'t4')
original<-do.call(cbind,lapply(params_t4,function(x) x[,1]))
estimated<-do.call(cbind,lapply(params_t4,function(x) x[,2]))
colnames(original)<-lapply(params_t4, function(x) gsub("[[:digit:]]","",rownames(x)[1])) #gets column names
colnames(estimated)<-colnames(original)
t4_matrix<-confusion_matrix(original,estimated,paramnames=c('learning rate','sensitivity','lapse'))+
  labs(title='Task 4')
ggsave(paste0(datadir,model4,'/t4_confusion_matrix.png'),t4_matrix)


```

Create overall figure


```{r}
t1_matrix + t2_matrix + guide_area() + t3_matrix + t4_matrix + plot_layout(guides='collect',ncol=3) + plot_annotation(tag_levels='A') & theme(legend.position='right')

ggsave(file=paste0(workingdir,'/figures/overall_confusion_matrix.png'),scale=0.9,width=10,height=7)
```

