---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

This is the setup chunk.

```{r}
#clears environment
rm(list=ls())

#libraries
library('rstan')
library('loo')
library('afex')
library('R.matlab')
library('permuco')
library('plyr')
library('reshape2')
library('RColorBrewer')
library('tidyverse')
library('effsize')
library('kableExtra')

#setup params
cluster=TRUE #if loading in from cluster
permute=FALSE

workingdir='C:/Users/apike/OneDrive - University College London/metaRL/'

source(paste0(workingdir,'scripts/bic.R'))
source(paste0(workingdir,'scripts/effect_sizes_text.R'))
source(paste0(workingdir,'scripts/plottext_cohend.R'))

```

Load in simulated data.
```{r}
load(file=paste0(workingdir,'simulated_data/data_task1')) #doesn't matter which one as you dont' use choices
simulated_data<-as.data.frame(simulated_data)
colnames(simulated_data)<- c('study','pat_con','id','trial','reward','pun','choices')
simulated_data<-transform(simulated_data,fullid=paste(study,id,sep='.'))
data_details<-simulated_data[simulated_data$trial==1,]
nsub_overall=length(unique(simulated_data$fullid))
ntrials=max(simulated_data$trial)
```
Use a script to compare model fits
Task 1
```{r}
task='t1'

source('analyse_modelfits_map.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse','1lr1t1d','1lr1t1d1p','2lr1t1d','2lr1t1d1p'),c(2,3,3,4,2,3,3,4,3,4,4,5,3,4,4,5))
p1<-analyse_modelfits_map(workingdir,model_details,ntrials=ntrials,task=task,singleprior=1)
```
Task 2
```{r}
task='t2'

source('analyse_modelfits_map.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse','1lr1t1d','1lr1t1d1p','2lr1t1d','2lr1t1d1p'),c(2,3,3,4,2,3,3,4,3,4,4,5))
p2<-analyse_modelfits_map(workingdir,model_details,ntrials=ntrials,task=task,singleprior=1)

```
Task 3
```{r}
task='t3'

source('analyse_modelfits_map.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse','1lr1t1d','1lr1t1d1p','2lr1t1d','2lr1t1d1p'),c(2,3,3,4,2,3,3,4,3,4,4,5,3,4,4,5))
p3<-analyse_modelfits_map(workingdir,model_details,ntrials=ntrials,task=task,singleprior=1)

```
Task 4
```{r}

task='t4'

source('analyse_modelfits_vba.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse','1lr1t1d','1lr1t1d1p','2lr1t1d','2lr1t1d1p'),c(2,3,3,4,2,3,3,4,3,4,4,5))
p4<-analyse_modelfits_map(workingdir,model_details,ntrials=ntrials,task=task,singleprior=1)

```

Task 5
```{r}

task='t5'

source('analyse_modelfits_map.R')
model_details<-cbind(c('1lr1t','1lr2t','2lr1t','2lr2t','1lr1s','2lr1s','1lr2s','2lr2s','1lr1s1lapse','1lr2s1lapse','2lr1s1lapse','2lr2s1lapse','1lr1t1d','1lr1t1d1p','2lr1t1d','2lr1t1d1p','1lr1s1lapse1bias','1lr1s1lapse2bias','1lr1s1lapse3bias','2lr2s1lapse1bias','2lr2s1lapse2bias','2lr2s1lapse3bias'),c(2,3,3,4,2,3,3,4,3,4,4,5,3,4,4,5,4,5,6,6,7,8))

p5<-analyse_modelfits_map(workingdir,model_details,ntrials=ntrials,task=task,singleprior=1)

```
Overall winning model

```{r}
load(paste0(workingdir,'/big_outputs/bic_df_map_singleprior_t1'))
bic_df_t1<-bic_df
load(paste0(workingdir,'/big_outputs/bic_df_map_singleprior_t2'))
bic_df_t2<-bic_df
load(paste0(workingdir,'/big_outputs/bic_df_map_singleprior_t3'))
bic_df_t3<-bic_df
load(paste0(workingdir,'/big_outputs/bic_df_map_singleprior_t4'))
bic_df_t4<-bic_df
load(paste0(workingdir,'/big_outputs/bic_df_map_singleprior_t5'))
bic_df_t5<-bic_df
bic_df<-data.frame(cbind(colSums(bic_df_t1),colSums(bic_df_t2),colSums(bic_df_t3),colSums(bic_df_t4),colSums(bic_df_t5)[1:16]))
names(bic_df)<-c('task1','task2','task3','task4')
min<-min(rowSums(bic_df))
max<-max(rowSums(bic_df))
model_names<-rownames(bic_df)
bic_df$model<-factor(model_names,levels=c(model_names),ordered=TRUE)
bic_df_long<-melt(bic_df)

modelcolours<-colorRampPalette(brewer.pal(9,'Set1'))(18)[1:length(bic_df$model)]
df<-data.frame(model_names,rowSums(bic_df[,1:4]))
names(df)<-c('model','total')
df$model<-factor(df$model,levels=c(model_names),ordered=TRUE)
bic_sums_unordered<-ggplot(df,aes(x=model,y=total,fill=model,label=model))+
  geom_bar(stat='identity')+
  labs(x='Model',y='Total BIC')+
  theme_classic()+
  theme(legend.position='none',axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+
  coord_cartesian(ylim = c(round_any(min(df$total),1000,floor), 
                           round_any(max(df$total),1000,ceiling)))+
  geom_text(data = df[which.min(df$total),], label = "*", nudge_y=100) +
  scale_fill_manual(values=modelcolours)
ggsave(paste0(workingdir,'/figures/bic_sums_map_unordered_sp.png'),scale=0.5,width=10,height=10)

#get bayes factor

ordered<-sort(rowSums(bic_df[,1:4]))

ordered[1]
ordered[2]

ordered[2]-ordered[1]

((ordered[2]-ordered[1])/2)
```



Analyse all parameters from all tasks together (omnibus): load data

```{r}
winning_model<-'1lr1t1d1p'

matlab_data_t1<-readMat(paste0(workingdir,'map/results_map_t1_sp.mat'))
map_t1=matlab_data_t1$results.map[,,1]
winning_model_t1=as.data.frame(map_t1[paste('map.',winning_model,sep='')])

matlab_data_t2<-readMat(paste0(workingdir,'map/results_map_t2_sp.mat'))
map_t2=matlab_data_t2$results.map[,,1]
winning_model_t2=as.data.frame(map_t2[paste('map.',winning_model,sep='')])

matlab_data_t3<-readMat(paste0(workingdir,'map/results_map_t3_sp.mat'))
map_t3=matlab_data_t3$results.map[,,1]
winning_model_t3=as.data.frame(map_t3[paste('map.',winning_model,sep='')])

matlab_data_t4<-readMat(paste0(workingdir,'map/results_map_t4_sp.mat'))
map_t4=matlab_data_t4$results.map[,,1]
winning_model_t4=as.data.frame(map_t4[paste('map.',winning_model,sep='')])

matlab_data_t5<-readMat(paste0(workingdir,'map/results_map_t5_sp.mat'))
map_t5=matlab_data_t5$results.map[,,1]
winning_model_t5=as.data.frame(map_t5[paste('map.',winning_model,sep='')])

data_details<-rbind(data_details[data_details$pat_con==1,],data_details[data_details$pat_con==0,])
  
```

Learning rate

```{r}
alpha_df<-cbind(winning_model_t1[,1],winning_model_t2[,1],winning_model_t3[,1],winning_model_t4[,1],winning_model_t5[,1])

alpha_df<-data.frame(data_details,alpha_df)

alpha_df<-melt(alpha_df,measure.vars = c('X1','X2','X3','X4','X5'))

names(alpha_df)<-c(names(data_details),'task','learning rate')

alpha_df$task<-as.numeric(alpha_df$task)
alpha_df$pat_con<-as.factor(alpha_df$pat_con)
alpha_df$task<-as.factor(alpha_df$task)
alpha_df$study<-as.factor(alpha_df$study)

alpha_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`learning rate`),2),iqr=round(IQR(`learning rate`),2))

if (permute==TRUE){
  anova<-permuco::aovperm(`learning rate` ~ pat_con * study * task + Error(fullid/(task)), data=alpha_df, method = "Rd_kheradPajouh_renaud")
} else {
  anova<-aov_car(`learning rate` ~ pat_con + study + task + Error(fullid/(task)), data=alpha_df)
}
print(anova$anova_table%>%data.frame(check.names = F)%>%select(`F`, `num Df`, `den Df`, `Pr(>F)`, `ges`)%>%mutate_if(is.numeric,round, digits=3)%>%kbl()%>%kable_minimal(full_width = F))

effect_sizes_text(workingdir,'omnibus','separate','map','learning rate','all',alpha_df)

#fval<-round(anova$anova_table$F[1],2)
#df<-paste0(anova$anova_table$`num Df`[1],',',anova$anova_table$`den Df`[1])
#pval<-ifelse(anova$anova_table$`Pr(>F)`[1]<.001,'< .001',round(anova$anova_table$`Pr(>F)`[1],3))

d<-cohen.d(alpha_df$`learning rate`[alpha_df$pat_con==1],alpha_df$`learning rate`[alpha_df$pat_con==0])
print(paste0('Cohen\'s d: ',round(d$estimate,2), '[', round(d$conf.int[1],2),',', round(d$conf.int[2],2), ']'))
d<-round(d$estimate,2)

plottext<-plottext_cohend(anova,d,permute)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")


p1<-ggplot(alpha_df,aes(x=pat_con,y=`learning rate`,group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE, color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Learning rate',fill='Group')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        scale_fill_manual(labels=c('Control','Patient'),values=c('#FC766AFF','#5B84B1FF'))+
        scale_y_continuous(breaks=c(seq(0,1,0.2)))+
                annotate(geom='text',x=1.5,y=1.1,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 1.02, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 1.05, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 1.02, yend = 1.05,
                     colour = "black") 
ggsave(paste0(workingdir,'/figures/alpha_overall_map.png'), scale=0.6,width=12,height=14)

```

inverse temperature

```{r}
beta_df<-cbind(winning_model_t1[,2],winning_model_t2[,2],winning_model_t3[,2],winning_model_t4[,2],winning_model_t5[,2])

beta_df<-data.frame(data_details,beta_df)

beta_df<-melt(beta_df,measure.vars = c('X1','X2','X3','X4','X5'))

names(beta_df)<-c(names(data_details),'task','inverse temperature')

beta_df$task<-as.numeric(beta_df$task)
beta_df$pat_con<-as.factor(beta_df$pat_con)
beta_df$task<-as.factor(beta_df$task)
beta_df$study<-as.factor(beta_df$study)

beta_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`inverse temperature`),2),iqr=round(IQR(`inverse temperature`),2))


if (permute==TRUE){
  anova<-permuco::aovperm(`inverse temperature` ~ pat_con * study * task + Error(fullid/(task)), data=beta_df, method = "Rd_kheradPajouh_renaud")
} else {
  anova<-aov_car(`inverse temperature` ~ pat_con + study + task + Error(fullid/(task)), data=beta_df)
}
print(anova$anova_table%>%data.frame(check.names = F)%>%select(`F`, `num Df`, `den Df`, `Pr(>F)`, `ges`)%>%mutate_if(is.numeric,round, digits=3)%>%kbl()%>%kable_minimal(full_width = F))

#fval<-round(anova$anova_table$F[1],2)
#df<-paste0(anova$anova_table$`num Df`[1],',',anova$anova_table$`den Df`[1])
#pval<-ifelse(anova$anova_table$`Pr(>F)`[1]<.001,'< .001',round(anova$anova_table$`Pr(>F)`[1],3))

effect_sizes_text(workingdir,'omnibus','separate','map','inverse temperature','all',beta_df)

d<-cohen.d(beta_df$`inverse temperature`[beta_df$pat_con==1],beta_df$`inverse temperature`[beta_df$pat_con==0])
print(paste0('Cohen\'s d: ',round(d$estimate,2), '[', round(d$conf.int[1],2),',', round(d$conf.int[2],2), ']'))
d<-round(d$estimate,2)


plottext<-plottext_cohend(anova,d,permute)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")


p2<-ggplot(beta_df,aes(x=pat_con,y=log(`inverse temperature`),group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE, color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Log inverse temperature',fill='Group')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        scale_fill_manual(labels=c('Control','Patient'),values=c('#FC766AFF','#5B84B1FF'))+
        annotate(geom='text',x=1.5,y=15,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 10, yend = 11,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 11, yend = 11,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 10, yend = 11,
                     colour = "black") 
ggsave(paste0(workingdir,'/figures/beta_overall_map.png'), scale=0.6,width=12,height=14)
```
Decay term

```{r}
decay_df<-cbind(winning_model_t1[,3],winning_model_t2[,3],winning_model_t3[,3],winning_model_t4[,3],winning_model_t5[,3])

decay_df<-data.frame(data_details,decay_df)

decay_df<-melt(decay_df,measure.vars = c('X1','X2','X3','X4','X5'))

names(decay_df)<-c(names(data_details),'task','decay')

decay_df$task<-as.numeric(decay_df$task)
decay_df$pat_con<-as.factor(decay_df$pat_con)
decay_df$task<-as.factor(decay_df$task)
decay_df$study<-as.factor(decay_df$study)

decay_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`decay`),2),iqr=round(IQR(`decay`),2))


if (permute==TRUE){
  anova<-permuco::aovperm(`decay` ~ pat_con * study * task + Error(fullid/(task)), data=decay_df, method = "Rd_kheradPajouh_renaud")
} else {
  anova<-aov_car(`decay` ~ pat_con + study + task + Error(fullid/(task)), data=decay_df)
}
print(anova$anova_table%>%data.frame(check.names = F)%>%select(`F`, `num Df`, `den Df`, `Pr(>F)`, `ges`)%>%mutate_if(is.numeric,round, digits=3)%>%kbl()%>%kable_minimal(full_width = F))

#fval<-round(anova$anova_table$F[1],2)
#df<-paste0(anova$anova_table$`num Df`[1],',',anova$anova_table$`den Df`[1])
#pval<-ifelse(anova$anova_table$`Pr(>F)`[1]<.001,'< .001',round(anova$anova_table$`Pr(>F)`[1],3))

effect_sizes_text(workingdir,'omnibus','separate','map','decay','all',decay_df)

d<-cohen.d(decay_df$`decay`[decay_df$pat_con==1],decay_df$`decay`[decay_df$pat_con==0])
print(paste0('Cohen\'s d: ',round(d$estimate,2), '[', round(d$conf.int[1],2),',', round(d$conf.int[2],2), ']'))
d<-round(d$estimate,2)

#plottext<-paste0("list(italic(F)[list(",df,")] == ",fval, ", italic(p) ",pval,", Cohens~italic(d) == ",d,")")

plottext<-plottext_cohend(anova,d,permute)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")


p3<-ggplot(decay_df,aes(x=pat_con,y=`decay`,group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE, color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Decay',fill='Group')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        scale_fill_manual(labels=c('Control','Patient'),values=c('#FC766AFF','#5B84B1FF'))+
        scale_y_continuous(breaks=c(seq(0,1,0.2)))+
        annotate(geom='text',x=1.5,y=1.1,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 1.02, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 1.05, yend = 1.05,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 1.02, yend = 1.05,
                     colour = "black") 
ggsave(paste0(workingdir,'/figures/decay_overall_map.png'), scale=0.6,width=12,height=14)

```
Perseverance
```{r}
perseverance_df<-cbind(winning_model_t1[,4],winning_model_t2[,4],winning_model_t3[,4],winning_model_t4[,4],winning_model_t5[,4])

perseverance_df<-data.frame(data_details,perseverance_df)

perseverance_df<-melt(perseverance_df,measure.vars = c('X1','X2','X3','X4','X5'))

names(perseverance_df)<-c(names(data_details),'task','perseverance')

perseverance_df$task<-as.numeric(perseverance_df$task)
perseverance_df$pat_con<-as.factor(perseverance_df$pat_con)
perseverance_df$task<-as.factor(perseverance_df$task)
perseverance_df$study<-as.factor(perseverance_df$study)

perseverance_df %>%
  group_by(pat_con)%>%
  summarise(median=round(median(`perseverance`),2),iqr=round(IQR(`perseverance`),2))


if (permute==TRUE){
  anova<-permuco::aovperm(`perseverance` ~ pat_con * study * task + Error(fullid/(task)), data=perseverance_df, method = "Rd_kheradPajouh_renaud")
} else {
  anova<-aov_car(`perseverance` ~ pat_con + study + task + Error(fullid/(task)), data=perseverance_df)
}
print(anova$anova_table%>%data.frame(check.names = F)%>%select(`F`, `num Df`, `den Df`, `Pr(>F)`, `ges`)%>%mutate_if(is.numeric,round, digits=3)%>%kbl()%>%kable_minimal(full_width = F))

#fval<-round(anova$anova_table$F[1],2)
#df<-paste0(anova$anova_table$`num Df`[1],',',anova$anova_table$`den Df`[1])
#pval<-ifelse(anova$anova_table$`Pr(>F)`[1]<.001,'< .001',round(anova$anova_table$`Pr(>F)`[1],3))

effect_sizes_text(workingdir,'omnibus','separate','map','perseverance','all',perseverance_df)

d<-cohen.d(perseverance_df$`perseverance`[perseverance_df$pat_con==1],perseverance_df$`perseverance`[perseverance_df$pat_con==0])
print(paste0('Cohen\'s d: ',round(d$estimate,2), '[', round(d$conf.int[1],2),',', round(d$conf.int[2],2), ']'))
d<-round(d$estimate,2)

#plottext<-paste0("list(italic(F)[list(",df,")] == ",fval, ", italic(p) ",pval,", Cohens~italic(d) == ",d,")")

plottext<-plottext_cohend(anova,d,permute)

source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")


p4<-ggplot(perseverance_df,aes(x=pat_con,y=`perseverance`,group=pat_con,fill=pat_con))+
        geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
        geom_point(position = position_jitter(width = .15), size = .25, alpha = 0.1,
                   show.legend = FALSE, color='grey')+
        geom_boxplot(aes(fill=NA),width = .1, outlier.shape = NA, show.legend=FALSE) +
        #stat_summary(fun = mean, geom="point", shape=20, size=2, color="black",
        #             show.legend = FALSE) +
        #stat_summary(fun.data = mean_se, geom = "errorbar", width=0.1,
        #             show.legend = FALSE)+
        labs(x='Group',y='Perseverance',fill='Group')+
        theme_classic()+
        theme(text=element_text(size=16))+
        scale_x_discrete(labels=c("0"="Control","1"="Patient"))+
        scale_fill_manual(labels=c('Control','Patient'),values=c('#FC766AFF','#5B84B1FF'))+
        scale_y_continuous(breaks=c(seq(0,1,0.2)))+
        annotate(geom='text',x=1.5,y=13,
                 label=as.character(plottext),
                 parse=TRUE)+
        geom_segment(x = 1, xend = 1, 
                     y = 10, yend = 11,
                     colour = "black") +
        geom_segment(x = 1, xend = 2, 
                     y = 11, yend = 11,
                     colour = "black") +
        geom_segment(x = 2, xend = 2, 
                     y = 10, yend = 11,
                     colour = "black")+
        ylim(-15,15)
ggsave(paste0(workingdir,'/figures/perseverance_overall_map.png'), scale=0.6,width=12,height=14)

```

Combine all plots together

```{r}
library('patchwork')

p1 + p2 + p3 + p4 + plot_annotation(tag_levels='A',) + plot_layout(guides='collect') & scale_color_manual(values='grey')

ggsave(paste0(workingdir,'/figures/params_overall_map_sp.png'), scale=0.6, width=18, height =8)

```
Get genchoices for best fitting model
```{r}
source(paste0(workingdir,'/scripts/generate_choices_fromfit.R'))
model='1lr1t1d1p'
tasklist<-c('task1','task2','task3','task4','task5')

overall<-list()
matching<-list()
accuracy<-list()

for (t in 1:length(tasklist)){
  task<-tasklist[t]
  overall[[t]]<-generate_choices_fromfit(model,task,workingdir,nprior=1,method='map')
  matching[[t]]<-overall[[t]][[1]]
  accuracy[[t]]<-overall[[t]][[2]]
}


names(matching)<-tasklist
matching_df<-
  bind_rows(matching,.id='task')

names(accuracy)=tasklist[1:4]
accuracy_df<-
  bind_rows(accuracy,.id='task')%>%
  pivot_longer(cols=c('synthetic_accuracy','bank_accuracy'),names_to='type')

accuracyplot<-ggplot(accuracy_df,aes(x=trial,y=value,colour=type))+
  geom_point()+
  facet_wrap(.~task)+
  theme_classic()+
  labs(x='Trial number',y='Correct option chosen')+
  scale_colour_discrete(labels=c('Bank data','Synthetic choices \n from 1lr1t1d1p'))+
  ylim(c(0,1))
ggsave(filename=paste0(workingdir,'/figures/map1_replication_accuracy.png'),accuracyplot,width=10,height=6)

densityplot<-ggplot(matching_df,aes(x=replicated,group=task,colour=task))+
  geom_density()+
  theme_classic()
ggsave(filename=paste0(workingdir,'/figures/map1_replication.png'))

correlations<-matching_df%>%
  group_by(task)%>%
  summarize(reward=cor(total_rewards.x,total_rewards.y),
            punishment=cor(total_punishments.x,total_punishments.y))%>%
  pivot_longer(cols=c(reward,punishment),names_to = 'outcome',values_to = 'correlation')%>%
  mutate(outcome=factor(outcome,levels=c('reward','punishment')))

correlationplot<-ggplot(correlations,aes(x=task,y=correlation,group=outcome,colour=outcome))+
  geom_point()+
  theme_classic()+
  ylim(c(0,1))+
  scale_colour_manual(values=c('forestgreen','red'))+
  labs(x='task',y='Correlation coefficient between \n bank choices and 1lr1t1d1p choices')
ggsave(filename=paste0(workingdir,'/figures/map1_replication_rewards.png'))

accuracyplot + correlationplot + plot_annotation(tag_levels = 'A')
ggsave(filename=paste0(workingdir,'/figures/map1_choice_replication_plot.png'),width=12,height=4)
```